project:
  type: website

website:
  title: "MW Physics & Math"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: solutions.qmd
        text: Solutions
      - href: simulations.qmd 
        text: Simulations
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

