# Netlify configuration file

[build]
image = "ubuntu-jammy-22.04"
command = "quarto render"
publish = "_site"

[context.production.environment]
QUARTO_VERSION = "1.4.553"

[context.deploy-preview.environment]
QUARTO_VERSION = "1.4.553"